<a href="https://colab.research.google.com/github/TatanPerez/4101135-Modelado_Simulacion/blob/main/Mini_Proyectos/Mini_Proyecto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Informe interactivo:  **[Vibraciones libres de un eje rotatorio con no linealidades (modelo reducido tipo Duffing acoplado)](https://www.researchgate.net/profile/Seyyed-Ali-Asghar-Hosseini-syd-ly-asghr-hsyny/publication/222953279_Free_vibrations_analysis_of_a_rotating_shaft_with_nonlinearities_in_curvature_and_inertia/links/59e88fcdaca272bc4240a075/Free-vibrations-analysis-of-a-rotating-shaft-with-nonlinearities-in-curvature-and-inertia.pdf?_sg%5B0%5D=started_experiment_milestone&origin=journalDetail)**

Wilmer Sebastian Perez Cuastumal

Universidad Nacional de Colombia

21/09/2025

---

## Resumen
Este informe presenta el análisis de vibraciones libres de un eje rotatorio utilizando un modelo
reducido no lineal del tipo **Duffing acoplado**, derivado de la discretización modal de un eje continuo.
A partir de las ecuaciones de movimiento obtenidas en el artículo de referencia, se realiza un análisis
cualitativo de equilibrios y estabilidad, así como simulaciones numéricas mediante `solve_ivp`.
Se incluyen visualizaciones en el dominio temporal y en el espacio de estados para diferentes
condiciones iniciales y parámetros de operación (velocidad de giro, amortiguamiento, rigidez, etc.).

---

## Introducción
El estudio de vibraciones en rotores es esencial en el diseño de máquinas rotatorias,
ya que fenómenos como la inestabilidad dinámica, el **whirl** (precesión hacia adelante o atrás) y
las resonancias pueden comprometer el desempeño y la seguridad de equipos industriales.
En particular, los efectos de **no linealidad en curvatura e inercia** producen desviaciones
respecto al comportamiento lineal, que deben modelarse con ecuaciones diferenciales no lineales.

El artículo *Free vibrations analysis of a rotating shaft with nonlinearities in curvature and inertia*
(Hosseini & Khadem, 2009) presenta un modelo continuo basado en la teoría de Euler-Bernoulli,
posteriormente reducido mediante el método de Galerkin. El resultado es un sistema dinámico
acoplado en dos direcciones transversales, con términos cúbicos característicos de los osciladores
tipo Duffing.

---

## Descripción del fenómeno
El eje rotatorio se deforma lateralmente en dos planos ortogonales, descritos por las coordenadas
generalizadas V(t) y W(t). La rotación introduce:
- **acoplamiento giroscópico**, que relaciona las velocidades transversales,
- **no linealidades cúbicas** en la rigidez efectiva, tanto individuales (V³, W³) como acopladas (V·W², W·V²),
- **efectos de amortiguamiento** que limitan la amplitud de las vibraciones.

Este fenómeno se traduce en trayectorias complejas en el espacio de estados, que pueden incluir
oscilaciones estables, inestables y patrones de precesión.

---

## Modelo analítico y análisis cualitativo
El modelo reducido no lineal es:

$$ M \ddot{V} + c \dot{V} + K V + G \Omega \dot{W} + \gamma V^3 + \eta V W^2 = 0 $$
$$ M \ddot{W} + c \dot{W} + K W - G \Omega \dot{V} + \gamma W^3 + \eta W V^2 = 0 $$

donde:
- **V, W**: desplazamientos transversales,
- **M**: masa modal efectiva,
- **c**: amortiguamiento modal,
- **K**: rigidez modal,
- **G**: coeficiente giroscópico,
- **Ω**: velocidad angular de giro,
- **γ**: coeficiente cúbico de rigidez no lineal,
- **η**: coeficiente de acoplamiento cúbico.

Según la no-dimensionalización y la discretización del artículo:

- M = 1 + n²·π²·I₂   → masa modal efectiva,
- K = n⁴·π⁴          → rigidez modal,
- G = 2·n²·π²·I₂     → coeficiente giroscópico,
- γ ≈ n⁶·π⁶          → coeficiente cúbico principal,
- η                  → coeficientes mixtos cúbicos,
- c                  → amortiguamiento modal,
- Ω                  → velocidad de giro.

El análisis cualitativo se centra en la búsqueda de equilibrios (soluciones estacionarias)
y su estabilidad lineal mediante el cálculo de autovalores del Jacobiano.

---

## Modelo computacional y simulaciones
El sistema de ecuaciones se implementa en Python transformándolo a primer orden,
con la función `system_rhs`. Para resolver problemas de valor inicial (PVI),
se emplea el integrador `solve_ivp` de SciPy. Además, se programan rutinas
de graficado para:
- series temporales de V y W,
- diagramas de fase (V vs V̇, W vs Ẇ, V vs W),
- simulaciones interactivas mediante `ipywidgets.interact`.

---

## Análisis de resultados y conclusiones
- El equilibrio trivial (V = W = 0) es estable para ciertos rangos de parámetros,
  pero puede perder estabilidad cuando aumentan Ω o disminuye c.
- El acoplamiento giroscópico desplaza frecuencias naturales y puede inducir
  fenómenos de **whirl** hacia adelante o hacia atrás.
- Los términos no lineales (γ, η) producen rigidez dependiente de la amplitud,
  típica de sistemas Duffing, generando oscilaciones de amplitud limitada.
- Las simulaciones permiten explorar diferentes escenarios y visualizar la
  transición de regímenes estables a inestables.

---

## Referencias
- Hosseini, S. M., & Khadem, S. E. (2009). *Free vibrations analysis of a rotating shaft
  with nonlinearities in curvature and inertia*. Mechanism and Machine Theory, 44(2), 272–288.
- Nayfeh, A. H., & Mook, D. T. (1979). *Nonlinear Oscillations*. Wiley.
- Rao, J. S. (2011). *Rotor Dynamics*. Springer.


Informe interactivo: Vibraciones libres de un eje rotatorio (modelo reducido tipo Duffing acoplado)

Este archivo está pensado para abrirse en Google Colab como un *Jupyter Notebook* (los bloques `# %%`
actúan como celdas). Contiene código Python para:
1. Análisis cualitativo (equilibrios y estabilidad analítica)
2. Simulaciones de PVI con `scipy.integrate.solve_ivp`
3. Gráficas temporales para diferentes condiciones iniciales
4. Diagramas en el espacio de estados para diferentes condiciones iniciales

---

**Modelo reducido**

El modelo matemático simplificado que representa las vibraciones laterales de un eje rotatorio con
no linealidades en curvatura e inercia es un sistema acoplado tipo Duffing:

$$ M \ddot{V} + c \dot{V} + K V + G \Omega \dot{W} + \gamma V^3 + \eta V W^2 = 0 $$
$$ M \ddot{W} + c \dot{W} + K W - G \Omega \dot{V} + \gamma W^3 + \eta W V^2 = 0 $$

donde:
- **V, W**: desplazamientos laterales del eje en dos planos ortogonales (x e y).
- **V_d, W_d**: velocidades laterales.
- **V_dd, W_dd**: aceleraciones laterales.

---

**Significado de los parámetros físicos**

- **M**: masa modal efectiva (adimensional). Incluye la inercia del eje y el efecto giroscópico
  del giro.
- **c**: coeficiente de amortiguamiento viscoso. Modela la disipación de energía por fricción.
- **K**: rigidez modal. Representa la resistencia del eje a deformarse lateralmente.
- **G**: coeficiente giroscópico. Está ligado a la inercia rotacional transversal *I₂*.
- **Ω (Omega)**: velocidad angular de giro del eje. Aparece en los términos giroscópicos
  que acoplan V y W, dando lugar a fenómenos de *whirl* (precesión hacia adelante o hacia atrás).
- **γ (gamma)**: coeficiente de rigidez no lineal cúbica (tipo Duffing). Surge de la curvatura
  no lineal del eje.
- **η (eta)**: coeficiente de acoplamiento no lineal. Modela la interacción cúbica entre las dos
  direcciones de desplazamiento (términos mixtos V·W² y W·V²).

---

**Según la no-dimensionalización y la discretización del artículo:**

- M = 1 + n²·π²·I₂  → masa modal efectiva.
- K = n⁴·π⁴        → rigidez modal.
- G = 2·n²·π²·I₂   → coeficiente giroscópico en la forma lineal usada.
- γ ≈ n⁶·π⁶        → coeficiente cúbico principal que produce la dureza no lineal.
- η                → agrupa los coeficientes de los términos mixtos cúbicos
(de orden similar a γ en la escala).
- c                → amortiguamiento modal.
- Ω                → velocidad de giro del eje.

* * *

Instrucciones de uso
- Ejecuta las celdas en orden.
- Usa la celda interactiva al final para variar parámetros y condiciones iniciales.
- Observa cómo cambian las trayectorias en el tiempo y en el espacio de estados.


In [ ]:
# Dependencias
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
from ipywidgets import interact, FloatSlider, IntSlider, fixed, Checkbox
import sympy as sp

## Definición del sistema (función RHS)
Definimos la función que devuelve las derivadas del sistema de 1er orden.


In [18]:
def system_rhs(t, y, params):
    """
    y = [V, Vdot, W, Wdot]
    params: dict con claves M, c, K, G, Omega, gamma, eta
    """
    V, Vd, W, Wd = y
    M = params['M']
    c = params['c']
    K = params['K']
    G = params['G']
    Omega = params['Omega']
    gamma = params['gamma']
    eta = params['eta']

    # Ecuaciones (según signo y convención):
    Vdd = (-c*Vd - K*V - G*Omega*Wd - gamma*(V**3) - eta*V*(W**2)) / M
    Wdd = (-c*Wd - K*W + G*Omega*Vd - gamma*(W**3) - eta*W*(V**2)) / M

    return [Vd, Vdd, Wd, Wdd]


# ## Parámetros por defecto (puedes cambiarlos en la celda interactiva)

# %%
def default_params(n=1, I2=6.25e-4, c=0.05, Omega=10.0, eta_factor=0.2):
    """
    Construye parámetros M,K,G,gamma,eta a partir de los parámetros modalizados usados en el artículo.
    n: número de modo
    I2: momento diametral adimensional
    eta_factor: fracción del coeficiente cúbico principal para generar el término mixto
    """
    pi = np.pi
    M = 1.0 + (n**2)*(pi**2)*I2
    K = (n**4)*(pi**4)
    G = 2.0*(n**2)*(pi**2)*I2
    gamma = (n**6)*(pi**6)
    eta = eta_factor * gamma
    return {'M': M, 'c': c, 'K': K, 'G': G, 'Omega': Omega, 'gamma': gamma, 'eta': eta}


# ## 1) Análisis cualitativo: encontrar equilibrios y estabilidad (analítico/simbólico)
# Buscaremos puntos de equilibrio (V*, W*, Vd*=0, Wd*=0) resolviendo las ecuaciones algebraicas.

def find_equilibria_symbolic(params):
    # Definimos variables simbólicas
    V, W = sp.symbols('V W', real=True)
    K = params['K']
    gamma = params['gamma']
    eta = params['eta']

    eq1 = sp.Eq(K*V + gamma*V**3 + eta*V*W**2, 0)
    eq2 = sp.Eq(K*W + gamma*W**3 + eta*W*V**2, 0)

    sols = sp.solve([eq1, eq2], [V, W], dict=True)
    return sols

# %%
# Jacobiano del sistema en la forma de primer orden (simbólico)
V, Vd, W, Wd = sp.symbols('V Vd W Wd')
M_s, c_s, K_s, G_s, Omega_s, gamma_s, eta_s = sp.symbols('M c K G Omega gamma eta')

# Variables de estado: x = [V, Vd, W, Wd]
# Formulamos las RHS simbólicamente para poder derivar el jacobiano
Vdd_s = (-c_s*Vd - K_s*V - G_s*Omega_s*Wd - gamma_s*V**3 - eta_s*V*W**2) / M_s
Wdd_s = (-c_s*Wd - K_s*W + G_s*Omega_s*Vd - gamma_s*W**3 - eta_s*W*V**2) / M_s

f1 = Vd
f2 = Vdd_s
f3 = Wd
f4 = Wdd_s

X = sp.Matrix([f1, f2, f3, f4])
states = sp.Matrix([V, Vd, W, Wd])

Jac = X.jacobian(states)


# Función que evalúa la estabilidad lineal en un punto de equilibrio (calcula autovalores del jacobiano).

# %%
def linear_stability_at_equilibrium(eq_point, params):
    # eq_point: dict {'V': val, 'W': val}
    subs = {V: eq_point['V'], W: eq_point['W'], Vd: 0, Wd: 0,
            M_s: params['M'], c_s: params['c'], K_s: params['K'],
            G_s: params['G'], Omega_s: params['Omega'],
            gamma_s: params['gamma'], eta_s: params['eta']}
    J_num = np.array(Jac.subs(subs).evalf(), dtype=float)
    eigvals, eigvecs = np.linalg.eig(J_num)
    return eigvals, J_num


# ## 2) Simulaciones de PVI con solve_ivp
# Función que integra y devuelve la solución

# %%
def simulate_ivp(y0, t_span, params, rtol=1e-8, atol=1e-10, method='RK45'):
    sol = solve_ivp(lambda t,y: system_rhs(t,y,params), t_span, y0,
                    method=method, rtol=rtol, atol=atol, dense_output=True)
    return sol


# ## Funciones de graficado

# %%
def plot_time_series(sol, vars_to_plot=('V','W'), figsize=(10,4)):
    t = sol.t
    y = sol.y
    plt.figure(figsize=figsize)
    if 'V' in vars_to_plot:
        plt.plot(t, y[0,:], label='V (desplazamiento)')
    if 'Vdot' in vars_to_plot:
        plt.plot(t, y[1,:], label='V_dot')
    if 'W' in vars_to_plot:
        plt.plot(t, y[2,:], label='W (desplazamiento)')
    if 'Wdot' in vars_to_plot:
        plt.plot(t, y[3,:], label='W_dot')
    plt.xlabel('t')
    plt.legend()
    plt.grid(True)
    plt.show()

# %%
def plot_phase_space(sol, kind='V_Vdot'):
    y = sol.y
    plt.figure(figsize=(5,5))
    if kind == 'V_Vdot':
        plt.plot(y[0,:], y[1,:])
        plt.xlabel('V')
        plt.ylabel('V_dot')
    elif kind == 'W_Wdot':
        plt.plot(y[2,:], y[3,:])
        plt.xlabel('W')
        plt.ylabel('W_dot')
    elif kind == 'V_W':
        plt.plot(y[0,:], y[2,:])
        plt.xlabel('V')
        plt.ylabel('W')
    plt.grid(True)
    plt.show()


# ## 3) Ejemplo: análisis analítico y simulación con parámetros por defecto

# %%
# Parámetros por defecto
params = default_params(n=1, I2=6.25e-4, c=0.05, Omega=10.0, eta_factor=0.1)
print('Parámetros usados (ejemplo):')
for k,v in params.items():
    print(f"  {k} = {v}")

# Encontrar equilibrios simbólicamente (puede devolver soluciones evidentes como (0,0))
sols = find_equilibria_symbolic(params)
print('\nEquilibrios simbólicos encontrados:')
for s in sols:
    print(s)

# Estabilidad lineal en el equilibrio trivial (0,0)
evals, Jnum = linear_stability_at_equilibrium({'V':0,'W':0}, params)
print('\nJacobiano linealizado en (0,0):')
print(Jnum)
print('\nAutovalores en (0,0):')
print(evals)




# ## 4) Celda interactiva: correr simulaciones cambiando parámetros y condiciones iniciales
# Usa los sliders para variar condiciones y ver resultados. Esta celda llama a `solve_ivp` cada vez que
# cambias un parámetro del `interact`.

# %%
@interact(
    V0=FloatSlider(min=-0.05, max=0.05, step=0.001, value=0.01, description='V(0)'),
    Vd0=FloatSlider(min=-1.0, max=1.0, step=0.01, value=0.0, description="V'(0)"),
    W0=FloatSlider(min=-0.05, max=0.05, step=0.001, value=0.0, description='W(0)'),
    Wd0=FloatSlider(min=-1.0, max=1.0, step=0.01, value=0.0, description="W'(0)"),
    Omega=FloatSlider(min=0.0, max=100.0, step=1.0, value=10.0, description='Omega'),
    c=FloatSlider(min=0.0, max=1.0, step=0.01, value=0.05, description='c'),
    I2=FloatSlider(min=0.0, max=0.01, step=1e-4, value=6.25e-4, description='I2'),
    eta_factor=FloatSlider(min=0.0, max=1.0, step=0.01, value=0.1, description='eta_fac'),
    tmax=FloatSlider(min=1.0, max=200.0, step=1.0, value=100.0, description='tmax'),
    plot_time=Checkbox(value=True, description='Mostrar serie temporal'),
    plot_phase=Checkbox(value=True, description='Mostrar espacio de estados')
)
def run_interactive(V0, Vd0, W0, Wd0, Omega, c, I2, eta_factor, tmax, plot_time, plot_phase):
    params = default_params(n=1, I2=I2, c=c, Omega=Omega, eta_factor=eta_factor)
    y0 = [V0, Vd0, W0, Wd0]
    t_span = (0.0, float(tmax))
    sol = simulate_ivp(y0, t_span, params, method='RK45')

    if plot_time:
        plot_time_series(sol, vars_to_plot=('V','W','Vdot','Wdot'))
    if plot_phase:
        plot_phase_space(sol, kind='V_Vdot')
        plot_phase_space(sol, kind='W_Wdot')
        plot_phase_space(sol, kind='V_W')


Parámetros usados (ejemplo):
  M = 1.0061685027506808
  c = 0.05
  K = 97.40909103400242
  G = 0.012337005501361699
  Omega = 10.0
  gamma = 961.3891935753043
  eta = 96.13891935753043

Equilibrios simbólicos encontrados:
{V: 0.0, W: 0.0}

Jacobiano linealizado en (0,0):
[[ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-9.68119065e+01 -4.96934657e-02  0.00000000e+00 -1.22613712e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  1.22613712e-01 -9.68119065e+01 -4.96934657e-02]]

Autovalores en (0,0):
[-0.02500155+9.90077065j -0.02500155-9.90077065j -0.02469192+9.77815694j
 -0.02469192-9.77815694j]


interactive(children=(FloatSlider(value=0.01, description='V(0)', max=0.05, min=-0.05, step=0.001), FloatSlide…

Observaciones rápidas:
- Si todos los autovalores tienen parte real negativa, el equilibrio es linealmente estable.
- En presencia de giro (Omega) los términos giroscópicos pueden desplazar modos y producir acoplamientos
  que generan oscilaciones con crecimiento o batido según otros parámetros.
